// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV81tMJLudQ4jpS7QJjzHpeHQ_iMrvumk',
    appId: '1:631474498647:web:faa27ac6d99d254b48c712',
    messagingSenderId: '631474498647',
    projectId: 'sliding-master-5da96',
    authDomain: 'sliding-master-5da96.firebaseapp.com',
    storageBucket: 'sliding-master-5da96.appspot.com',
    measurementId: 'G-5Y7J1RM3Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe37EB2mV0QybgzL_PBEgK_3pC-f7MYVk',
    appId: '1:631474498647:android:ece9d22d07a7f61f48c712',
    messagingSenderId: '631474498647',
    projectId: 'sliding-master-5da96',
    storageBucket: 'sliding-master-5da96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuuSifR8NpMW2ZvT_Dbu1vwtXF_Y_kyjM',
    appId: '1:631474498647:ios:cf12c00ede05d9c648c712',
    messagingSenderId: '631474498647',
    projectId: 'sliding-master-5da96',
    storageBucket: 'sliding-master-5da96.appspot.com',
    iosBundleId: 'com.app.slidingMaster',
  );

}